# Generated by Django 6.0 on 2026-01-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10, unique=True)),
                ('created_otp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
